### ISSUE TITLE
please update your systemd service

### ISSUE THREAD

**Issue by Jskarie** [Matt-Deacalion/systemd-django#1]
Your service file shows up as the top hit on google when I search for a django systemd service.  Please fix it to help others(and I assume yourself as well)

In your configuration when postgres gets shutdown(updated) then started your gunicorn service will be shutdown and not restarted.  Here is the information on how to fix it.  

[serverfault explaining problem/solution](https://serverfault.com/questions/773812/start-systemd-service-on-start-of-requirement?noredirect=1&lq=1
)

**Comment by Matt-Deacalion** [comment]
The fix on the Stack Exchange website doesn't work for the problem you mentioned. If you have success, feel free to issue a pull request.
